name: MSBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Build all and run tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: HelperScripts\BuildAllAndRunTests.bat
